-- Footnote text is lost on every reload: the footnotes table has never had
-- anywhere to store the fn-xxx marker id that the entry's content actually
-- references (via [^fn-xxx]). On save, saveEntry() only ever wrote
-- label/content/sort_order; on load, the code fell back to the row's own
-- auto-generated primary key as if it were that marker id, which it never
-- is, so getOrderedFootnotesToRender()'s lookup by marker id always misses
-- and every footnote renders with empty text after a reload or publish.
--
-- margin_notes already solved the identical problem with its own
-- block_key column ("corresponds to marginNotesData key") — this mirrors
-- that exact pattern for footnotes.
--
-- Existing footnote rows never had their marker id stored, so block_key
-- can't be backfilled directly from this table alone — but the content
-- itself is NOT lost: label/content/sort_order were saved correctly, and
-- sort_order was assigned in the same order the [^fn-xxx] markers appear
-- in the entry's own content. A row's marker id is recoverable by matching
-- its sort_order position against the Nth [^fn-...] occurrence in that
-- entry's content — worth doing deliberately as a follow-up script, not
-- assumed lost and not attempted inline in this migration.
--
-- IF NOT EXISTS: safe to run more than once, and safe to run against a
-- database this has already reached by another path.

alter table footnotes add column if not exists block_key text;
